package talk;


/**
* talk/chatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talk.idl
* jeudi 2 novembre 2017 16 h 53 CET
*/

public interface chatOperations 
{
  void diffuserMessage (String message);
  void enregistrer (String idObj);
} // interface chatOperations
