package talk;

/**
* talk/chatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talk.idl
* jeudi 2 novembre 2017 16 h 53 CET
*/

public final class chatHolder implements org.omg.CORBA.portable.Streamable
{
  public talk.chat value = null;

  public chatHolder ()
  {
  }

  public chatHolder (talk.chat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = talk.chatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    talk.chatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return talk.chatHelper.type ();
  }

}
