package talk;


/**
* talk/clientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talk.idl
* jeudi 2 novembre 2017 16 h 53 CET
*/

public abstract class clientPOA extends org.omg.PortableServer.Servant
 implements talk.clientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("afficherMessage", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // talk/client/afficherMessage
       {
         String message = in.read_string ();
         this.afficherMessage (message);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:talk/client:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public client _this() 
  {
    return clientHelper.narrow(
    super._this_object());
  }

  public client _this(org.omg.CORBA.ORB orb) 
  {
    return clientHelper.narrow(
    super._this_object(orb));
  }


} // class clientPOA
