package talk;

/**
* talk/clientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talk.idl
* jeudi 2 novembre 2017 16 h 53 CET
*/

public final class clientHolder implements org.omg.CORBA.portable.Streamable
{
  public talk.client value = null;

  public clientHolder ()
  {
  }

  public clientHolder (talk.client initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = talk.clientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    talk.clientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return talk.clientHelper.type ();
  }

}
