package talk;


/**
* talk/clientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talk.idl
* jeudi 2 novembre 2017 16 h 53 CET
*/

public interface clientOperations 
{
  void afficherMessage (String message);
} // interface clientOperations
