package talk;


/**
* talk/clientHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talk.idl
* jeudi 2 novembre 2017 16 h 53 CET
*/

abstract public class clientHelper
{
  private static String  _id = "IDL:talk/client:1.0";

  public static void insert (org.omg.CORBA.Any a, talk.client that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static talk.client extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (talk.clientHelper.id (), "client");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static talk.client read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_clientStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, talk.client value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static talk.client narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof talk.client)
      return (talk.client)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      talk._clientStub stub = new talk._clientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static talk.client unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof talk.client)
      return (talk.client)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      talk._clientStub stub = new talk._clientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
